"""

Problem Statement#
  You have to implement the is_formation_possible() function which will find whether a given word can be formed by combining two words from a dictionary. We assume that all words are in lower case.

Input#
  A list and a query word containing lowercase characters.

Output#
  Returns True if the given word can be generated by combining two words from the list.

Sample Input#
  lst = ["the", "hello", "there", "answer", "any",
         "by", "world", "their","abc"]

  word = "helloworld"

Sample Output#
  True

"""

def is_formation_possible(lst, word):
    
    d = {i:1 for i in lst}

    for i in range(len(word)):
        part1 = word[:i+1]
        part2 = word[i+1:]

        if part1 in d and part2 in d:
            return True

    return False
    

